version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./apps/backend
    ports:
      - "8000:8000"
    volumes:
      - ./public/mock:/app/mock # 挂载测试数据
    environment:
      - ENV=production

  # 前端服务
  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend
